/**
 * PDF Generator — creates a combined renter application packet.
 * Uses jsPDF to generate a multi-page application document.
 * All generation happens client-side (browser).
 */

import type { ApplicationData } from "@prisma/client";
import type { GroupWithMembers } from "@/types";

interface ListingInfo {
  address?: string | null;
  price?: number | null;
  beds?: number | null;
  baths?: number | null;
  landlordName?: string | null;
  landlordEmail?: string | null;
}

export interface ApplicationPacketInput {
  group: GroupWithMembers;
  listing: ListingInfo;
  applicants: ApplicationData[];
  generatedAt?: Date;
}

export async function generateApplicationPDF(input: ApplicationPacketInput): Promise<void> {
  // Dynamic import to avoid SSR issues
  const jsPDF = (await import("jspdf")).default;
  const autoTable = (await import("jspdf-autotable")).default;

  const { group, listing, applicants, generatedAt = new Date() } = input;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const MARGIN = 20;
  const PAGE_WIDTH = doc.internal.pageSize.getWidth();
  let y = MARGIN;

  const addText = (text: string, x: number, fontSize = 11, bold = false) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.text(text, x, y);
  };

  const addLine = () => {
    y += 4;
    doc.setDrawColor(200, 200, 200);
    doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
    y += 6;
  };

  const nextLine = (spacing = 7) => {
    y += spacing;
  };

  // ── Cover Page ──────────────────────────────────────────────────
  doc.setFillColor(99, 102, 241); // indigo
  doc.rect(0, 0, PAGE_WIDTH, 50, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("RENTAL APPLICATION PACKET", MARGIN, 25);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated by RoomieSearch • ${generatedAt.toLocaleDateString()}`, MARGIN, 38);

  y = 65;
  doc.setTextColor(0, 0, 0);

  // Property info
  addText("Property Information", MARGIN, 16, true);
  nextLine(8);

  autoTable(doc, {
    startY: y,
    head: [],
    body: [
      ["Address", listing.address ?? "N/A"],
      ["Rent", listing.price ? `$${listing.price.toLocaleString()}/month` : "N/A"],
      ["Beds / Baths", `${listing.beds ?? "?"} bed / ${listing.baths ?? "?"} bath`],
      ["Landlord", listing.landlordName ?? "N/A"],
      ["Landlord Email", listing.landlordEmail ?? "N/A"],
    ],
    theme: "grid",
    styles: { fontSize: 10 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 45 } },
    margin: { left: MARGIN, right: MARGIN },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;

  // Group info
  addText("Applying Group", MARGIN, 16, true);
  nextLine(8);

  autoTable(doc, {
    startY: y,
    head: [],
    body: [
      ["Group Name", group.name],
      ["Members", group.members.map((m) => m.user.name).join(", ")],
      ["Location Preference", group.location ?? "N/A"],
      ["Move-in Date", group.moveInDate ? new Date(group.moveInDate).toLocaleDateString() : "N/A"],
      ["Budget Range", group.budgetMin && group.budgetMax ? `$${group.budgetMin.toLocaleString()} – $${group.budgetMax.toLocaleString()}` : "N/A"],
    ],
    theme: "grid",
    styles: { fontSize: 10 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 45 } },
    margin: { left: MARGIN, right: MARGIN },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;

  // ── Applicant Pages ──────────────────────────────────────────────
  for (const applicant of applicants) {
    doc.addPage();
    y = MARGIN;

    // Header bar
    doc.setFillColor(238, 242, 255);
    doc.rect(0, 0, PAGE_WIDTH, 35, "F");
    doc.setTextColor(55, 48, 163);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(`${applicant.firstName ?? ""} ${applicant.lastName ?? ""}`, MARGIN, 20);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Applicant Profile", MARGIN, 30);

    y = 50;
    doc.setTextColor(0, 0, 0);

    // Personal info
    addText("Personal Information", MARGIN, 13, true);
    nextLine(6);

    autoTable(doc, {
      startY: y,
      head: [["Field", "Value"]],
      body: [
        ["Full Name", `${applicant.firstName ?? ""} ${applicant.lastName ?? ""}`.trim() || "N/A"],
        ["Email", applicant.email ?? "N/A"],
        ["Phone", applicant.phone ?? "N/A"],
        ["Current Address", applicant.currentAddress ?? "N/A"],
        ["Credit Score", applicant.creditScore?.toString() ?? "Not provided"],
      ],
      theme: "striped",
      headStyles: { fillColor: [99, 102, 241] },
      styles: { fontSize: 10 },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 55 } },
      margin: { left: MARGIN, right: MARGIN },
    });

    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;

    // Employment info
    addText("Employment & Income", MARGIN, 13, true);
    nextLine(6);

    autoTable(doc, {
      startY: y,
      head: [["Field", "Value"]],
      body: [
        ["Employer", applicant.employer ?? "N/A"],
        ["Job Title", applicant.jobTitle ?? "N/A"],
        ["Years at Job", applicant.employmentYears?.toString() ?? "N/A"],
        ["Annual Income", applicant.income ? `$${applicant.income.toLocaleString()}` : "N/A"],
        ["Monthly Income", applicant.income ? `$${Math.round(applicant.income / 12).toLocaleString()}` : "N/A"],
        ["Income-to-Rent Ratio", applicant.income && listing.price
          ? `${(applicant.income / 12 / listing.price).toFixed(1)}x`
          : "N/A"],
      ],
      theme: "striped",
      headStyles: { fillColor: [99, 102, 241] },
      styles: { fontSize: 10 },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 55 } },
      margin: { left: MARGIN, right: MARGIN },
    });

    // Guarantor info if present
    if (applicant.hasGuarantor) {
      y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
      addText("Guarantor Information", MARGIN, 13, true);
      nextLine(6);

      autoTable(doc, {
        startY: y,
        head: [["Field", "Value"]],
        body: [
          ["Guarantor Name", applicant.guarantorName ?? "N/A"],
          ["Guarantor Email", applicant.guarantorEmail ?? "N/A"],
          ["Guarantor Phone", applicant.guarantorPhone ?? "N/A"],
          ["Guarantor Income", applicant.guarantorIncome ? `$${applicant.guarantorIncome.toLocaleString()}` : "N/A"],
        ],
        theme: "striped",
        headStyles: { fillColor: [167, 139, 250] },
        styles: { fontSize: 10 },
        columnStyles: { 0: { fontStyle: "bold", cellWidth: 55 } },
        margin: { left: MARGIN, right: MARGIN },
      });
    }
  }

  // ── Summary Page ─────────────────────────────────────────────────
  doc.addPage();
  y = MARGIN;

  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, PAGE_WIDTH, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Combined Renter Summary", MARGIN, 22);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`${applicants.length} applicant(s) • ${group.name}`, MARGIN, 34);

  y = 55;
  doc.setTextColor(0, 0, 0);

  const totalIncome = applicants.reduce((acc, a) => acc + (a.income ?? 0), 0);
  const monthlyTotal = Math.round(totalIncome / 12);
  const avgCreditScore = applicants
    .filter((a) => a.creditScore)
    .reduce((acc, a, _, arr) => acc + (a.creditScore ?? 0) / arr.length, 0);

  const summaryBody = [
    ["Total Annual Income", `$${totalIncome.toLocaleString()}`],
    ["Total Monthly Income", `$${monthlyTotal.toLocaleString()}`],
    ["Rent", `$${listing.price?.toLocaleString() ?? "N/A"}/month`],
    ["Combined Income-to-Rent", listing.price ? `${(monthlyTotal / listing.price).toFixed(1)}x` : "N/A"],
    ["Average Credit Score", avgCreditScore ? Math.round(avgCreditScore).toString() : "Not provided"],
    ["Number of Applicants", applicants.length.toString()],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Summary", "Value"]],
    body: summaryBody,
    theme: "grid",
    headStyles: { fillColor: [99, 102, 241] },
    styles: { fontSize: 11 },
    columnStyles: { 0: { fontStyle: "bold" } },
    margin: { left: MARGIN, right: MARGIN },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20;

  // Footer disclaimer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "This document was generated by RoomieSearch and contains information provided by the applicants. All information is subject to verification.",
    MARGIN,
    y,
    { maxWidth: PAGE_WIDTH - MARGIN * 2 }
  );

  // Save
  const filename = `application-packet-${group.name.replace(/\s+/g, "-").toLowerCase()}-${Date.now()}.pdf`;
  doc.save(filename);
}
